const userData = {
    "2004":[
      "Tiesto",
      "Paul van Dyk",
      "Armin Van Buuren",
      "Sasha",
      "Ferry Corsten",
      "Hernan Cattaneo",
      "Christopher Lawrence",
      "John Digweed",
      "Paul Oakenfold",
      "Deep Dish",
      "Carl Cox",
      "Sander Kleinenberg",
      "ATB",
      "Judge Jules",
      "James Zabiela",
      "Marco V",
      "Roger Sanchez",
      "Benny Benassi",
      "Tall Paul",
      "Danny Howells",
      "Steve Lawler",
      "Erick Morillo",
      "Chris Liebing",
      "DJ Dan",
      "Eddie Halliwell",
      "Andy C",
      "Mauro Picotto",
      "Johan Gielen",
      "Lady Dana",
      "Lisa Lashes",
      "Adam Freeland",
      "Markus Schulz",
      "Yoji Biomehanika",
      "Sven Vth",
      "Bad Boy Bill",
      "James Holden",
      "Dave Clarke",
      "Blank & Jones",
      "Above & Beyond",
      "Danny Tenaglia",
      "Gabriel & Dresden",
      "TBC",
      "Nick Warren",
      "Richie Hawtin",
      "Laurent Garnier",
      "Pete Tong",
      "Jeff Mills",
      "Satoshi Tomiie",
      "Misstress Barbara",
      "Adam Beyer",
      "Fatboy Slim",
      "John '00' Fleming",
      "Plump DJ's",
      "David Morales",
      "Umek",
      "Lee Burridge",
      "Dave Seaman",
      "Fergie",
      "Matt Hardwick",
      "Slacker",
      "DJ Luna",
      "M.I.K.E",
      "DJ Rush",
      "Max Graham"
    ],
    "2005":[
      "Paul van Dyk",
      "Tiesto",
      "Armin Van Buuren",
      "Sasha",
      "Ferry Corsten",
      "John Digweed",
      "Hernan Cattaneo",
      "Deep Dish",
      "ATB",
      "Carl Cox",
      "Paul Oakenfold",
      "Richie Hawtin",
      "James Zabiela",
      "Christopher Lawrence",
      "Judge Jules",
      "Marco V",
      "Eddie Halliwell",
      "Erick Morillo",
      "Above & Beyond",
      "Sander Kleinenberg",
      "Markus Schulz",
      "Benny Benassi",
      "Sven Vth",
      "DJ Dan",
      "Danny Howells",
      "Infected Mushroom",
      "Roger Sanchez",
      "Mauro Picotto",
      "Gabriel & Dresden",
      "Steve Lawler",
      "Blank & Jones",
      "Yoji Biomehanika",
      "Chris Liebing",
      "Danny Tenaglia",
      "Nick Warren",
      "Dave Clarke",
      "James Holden",
      "Mario Piu",
      "David Guetta",
      "DJ Vibe",
      "Kai Tracid",
      "Bad Boy Bill",
      "Tall Paul",
      "Tiga",
      "DJ Yahel",
      "Andy Moor",
      "Ricardo Villalobos",
      "Ricky Stone",
      "Pete Tong",
      "Martin Garcia",
      "Frank T.R.A.X",
      "Timo Maas",
      "Laurent Garnier",
      "Desyn Masiello",
      "Victor Calderone",
      "Lisa Lashes",
      "Johan Gielen",
      "Matt Hardwick",
      "Misstress Barbara",
      "Fergie",
      "Armand Van Helden",
      "Michel De Hey",
      "Fatboy Slim",
      "Jeff Mills",
      "DJ Rush",
      "The Flash Brothers",
      "Adam Beyer",
      "Adam Beyer",
      "Donald Glaude",
      "Dave Seaman",
      "Andy C",
      "Chus & Ceballos",
      "John '00' Fleming",
      "Satoshi Tomiie",
      "DJ Tatana",
      "Astrix",
      "Lee Burridge",
      "M.I.K.E",
      "Lady Dana",
      "Umek",
      "Nic Fanciulli",
      "Rank 1",
      "BT",
      "Anne Savage",
      "Plump DJ's",
      "Miss Kitten",
      "Felix Da Housecat",
      "Christian Cambas",
      "Scot Project",
      "Cosmic Gate",
      "Matt Darey",
      "DJ Sammy",
      "Proteus",
      "DJ Luna",
      "Moshic",
      "Max Graham",
      "DJ Amadeus",
      "Gigi D'Agostino",
      "Marco Bailey",
      "Magda"
    ],
    "2006": [
      "Paul van Dyk",
      "Armin Van Buuren",
      "Tiesto",
      "Christopher Lawrence",
      "DJ Dan",
      "Ferry Corsten",
      "Sasha",
      "John Digweed",
      "Above & Beyond",
      "Deep Dish",
      "Carl Cox",
      "Infected Mushroom",
      "ATB",
      "Paul Oakenfold",
      "Hernan Cattaneo",
      "Judge Jules",
      "Eddie Halliwell",
      "Marco V",
      "Markus Schulz",
      "Gabriel & Dresden",
      "James Zabiela",
      "John Acquaviva",
      "Flash Brothers",
      "DJ Amadeus",
      "Erick Morillo",
      "Benny Benassi",
      "Sander Kleinenberg",
      "DJ Yahel",
      "Offer Nissim",
      "Andy Moor",
      "David Guetta",
      "Sander Van Doorn",
      "Richie Hawtin",
      "Gareth Emery",
      "Phil Kieran",
      "Nick Warren",
      "DJ Skazi",
      "Steve Lawler",
      "D-Formation",
      "Ricky Stone",
      "Astrix",
      "Roger Sanchez",
      "Bad Boy Bill",
      "Sven Vth",
      "The Thrillseekers",
      "Donald Glaude",
      "DJ Vibe",
      "Kyau & Albert",
      "Chris Liebing",
      "Tiga",
      "Matt Darey",
      "Bob Sinclair",
      "James Holden",
      "Lange",
      "Wrecked Machines",
      "Dion Mavath",
      "Pete Tong",
      "Danny Tenaglia",
      "George Acosta",
      "Blank & Jones",
      "DJ Sammy",
      "Joachim Garraud",
      "Timo Maas",
      "Matt Hardwick",
      "Frank T.R.A.X",
      "Steve Angello",
      "Danny Howells",
      "Simon Posford",
      "John Graham",
      "Desyn Masiello",
      "Mauro Picotto",
      "Menno De Jong",
      "BT",
      "Scott K",
      "Tall Paul",
      "M.I.K.E",
      "Filo & Peri",
      "DJ Tarkan",
      "Anderson Noise",
      "Fatboy Slim",
      "Serge Devant",
      "Umek",
      "Victor Calderone",
      "Darude",
      "Fergie",
      "Tallah 2XLC",
      "Ronski Speed",
      "Lee Burridge",
      "Mario Piu",
      "Axel Karakasis",
      "Steve Porter",
      "Yoji Biomehanika",
      "Axwell",
      "Stanton Warriors",
      "Dave Seaman",
      "Robbie Rivera",
      "Andy C",
      "Agnelli & Nelson",
      "Lisa Lashes",
      "Dave Clarke"
    ],
    "2007":[
      "Armin Van Buuren",
      "Tiesto",
      "John Digweed",
      "Paul van Dyk",
      "Sasha",
      "Above & Beyond",
      "Carl Cox",
      "Ferry Corsten",
      "Infected Mushroom",
      "David Guetta",
      "Deep Dish",
      "Paul Oakenfold",
      "Markus Schulz",
      "Hernan Cattaneo",
      "Sander Van Doorn",
      "Eddie Halliwell",
      "James Zabiela",
      "Astrix",
      "Richie Hawtin",
      "Marco V",
      "Judge Jules",
      "Fedde Le Grand",
      "Gabriel & Dresden",
      "Erick Morillo",
      "Roger Sanchez",
      "ATB",
      "Sven Vth",
      "Yahel",
      "Umek",
      "Andy Moor",
      "Gareth Emery",
      "Benny Benassi",
      "Axwell",
      "Mauro Picotto",
      "Sander Kleinenberg",
      "Eric Prydz",
      "Blank & Jones",
      "Bad Boy Bill",
      "Pete Tong",
      "DJ Vibe",
      "Tiga",
      "Steve Lawler",
      "Danny Tenaglia",
      "Ronski Speed",
      "Nic Fanciulli",
      "Steve Angello",
      "Nick Warren",
      "Matt Hardwick",
      "Ricardo Villalobos",
      "James Holden",
      "Mark Knight",
      "Marco Bailey",
      "Anderson Noise",
      "Lange",
      "Offer Nissim",
      "Kyau & Albert",
      "Justice",
      "Timo Maas",
      "Danny Howells",
      "Menno De Jong",
      "Bob Sinclair",
      "John Acquaviva",
      "Agnelli & Nelson",
      "Fatboy Slim",
      "Andy C",
      "Ricky Stone",
      "Donald Glaude",
      "Desyn Masiello",
      "Daft Punk",
      "Martin Solveig",
      "BT",
      "Chris Liebing",
      "Valentino Kanzyani",
      "Trentemeller",
      "Jeff Mills",
      "John Graham",
      "Robbie Rivera",
      "The Chemical Brothers",
      "Luciano",
      "Hype",
      "Lisa Lashes",
      "Filo & Peri",
      "Lee Burridge",
      "Armand Van Helden",
      "Magda",
      "Dave Seaman",
      "Victor Calderone",
      "Dave Clarke",
      "Richard Durand",
      "Westbam",
      "Sebastien Leger",
      "Chus & Ceballos",
      "Wally Lopez",
      "Adam Beyer",
      "Erol Alkan",
      "Laurent Garnier"
    ],
    "2008":[
      "Armin Van Buuren",
      "Tiesto",
      "Paul van Dyk",
      "Above & Beyond",
      "David Guetta",
      "Ferry Corsten",
      "Sasha",
      "Markus Schulz",
      "John Digweed",
      "Infected Mushroom",
      "Deadmau5",
      "Carl Cox",
      "Sander Van Doorn",
      "Paul Oakenfold",
      "Richie Hawtin",
      "Hernan Cattaneo",
      "James Zabiela",
      "Andy Moor",
      "Eddie Halliwell",
      "Axwell",
      "Eric Prydz",
      "Kyau & Albert",
      "Gareth Emery",
      "Sven Vth",
      "ATB",
      "Anderson Noise",
      "Joachim Garraud",
      "Bobina",
      "Fedde Le Grand",
      "Dubfire",
      "Aly & Fila",
      "Judge Jules",
      "Umek",
      "Matt Darey",
      "Ricky Stone",
      "Ricardo Villalobos",
      "Lange",
      "Daft Punk",
      "Benny Benassi",
      "Bob Sinclair",
      "Deep Dish",
      "Mark Knight",
      "Astrix",
      "Marco V",
      "The Thrillseekers",
      "Laidback Luke",
      "Danny Tenaglia",
      "Menno De Jong",
      "Marco Lenzi",
      "Andy C",
      "Offer Nissim",
      "Martin Solveig",
      "Adam Sheridan",
      "Sean Tyas",
      "DJ Feel",
      "Yahel",
      "Roger Sanchez",
      "DJ Shah",
      "Sander Kleinenberg",
      "John O'Callaghan",
      "Blank & Jones",
      "Cosmic Gate",
      "Steve Angello",
      "Simon Patterson",
      "Gabriel & Dresden",
      "Richard Durand",
      "Laurent Wolf",
      "Matt Hardwick",
      "Chris Liebing",
      "Erick Morillo",
      "DJ Hype",
      "Signum",
      "Justice",
      "Dirty South",
      "Wally Lopez",
      "Magda",
      "Lisa Lashes",
      "Pete Tong",
      "DJ Vibe",
      "Bad Boy Bill",
      "Tiddey",
      "Greg Downey",
      "Marcel Woods",
      "Nick Warren",
      "Solar System",
      "Skazi",
      "Mike Koglin",
      "Mauro Picotto",
      "Sebastien Leger",
      "The Chemical Brothers",
      "Steve Lawler",
      "Fatboy Slim",
      "Solarstone",
      "Astral Projection",
      "Leon Bolier",
      "Nic Fanciulli",
      "Ronski Speed",
      "Tocadisco",
      "Booka Shade",
      "Alex Morph & Woody Van Eyden"
    ],
    "2009":[
      "Armin Van Buuren",
      "Tiesto",
      "David Guetta",
      "Above & Beyond",
      "Paul van Dyk",
      "Deadmau5",
      "Ferry Corsten",
      "Markus Schulz",
      "Gareth Emery",
      "Sander Van Doorn",
      "ATB",
      "Infected Mushroom",
      "Sasha",
      "Axwell",
      "Andy Moor",
      "Bobina",
      "John Digweed",
      "Carl Cox",
      "Cosmic Gate",
      "Steve Angello",
      "Roger Shah",
      "Aly & Fila",
      "Paul Oakenfold",
      "John O'Callaghan",
      "Sebastian Ingrosso",
      "Benny Benassi",
      "Laidback Luke",
      "Richie Hawtin",
      "Fedde Le Grand",
      "DJ Feel",
      "Lange",
      "Hernan Cattaneo",
      "Daft Punk",
      "Eric Prydz",
      "Bob Sinclair",
      "Joachim Garraud",
      "Kyau & Albert",
      "James Zabiela",
      "Umek",
      "Christopher Lawrence",
      "Eddie Halliwell",
      "Simon Patterson",
      "Offer Nissim",
      "Judge Jules",
      "Sean Tyas",
      "Dubfire",
      "Martin Solveig",
      "Sven Vth",
      "Richard Durand",
      "Marco V",
      "Kaskade",
      "tyDi",
      "Erick Morillo",
      "Matt Darey",
      "Astrix",
      "Menno De Jong",
      "The Thrillseekers",
      "Nick Warren",
      "Dirty South",
      "Roger Sanchez",
      "Mark Knight",
      "Wally Lopez",
      "Leon Bolier",
      "Blank & Jones",
      "Justice",
      "Laurent Wolf",
      "Astral Projection",
      "Boys Noize",
      "Ronski Speed",
      "Sander Kleinenberg",
      "Ricardo Villalobos",
      "Chuckie",
      "Sharam",
      "Marcel Woods",
      "Lisa Lashes",
      "Moonbeam",
      "Rank 1",
      "Sebastien Leger",
      "Marcus Schossow",
      "Steve Lawler",
      "Skazi",
      "Super8 & Tab",
      "Pete Tong",
      "Tocadisco",
      "Sied Van Riel",
      "Tiga",
      "Daniel Kandi",
      "Mike Koglin",
      "Luciano",
      "Yahel",
      "Myon & Shane 54",
      "John B",
      "Simon Posford",
      "Fatboy Slim",
      "Robbie Rivera",
      "Antoine Clamaran",
      "Nic Fanciulli",
      "Gui Boratto",
      "Alex M.O.R.P.H.",
      "Andy C"
    ],
    "2010":[
      "Armin Van Buuren",
      "David Guetta",
      "Tiesto",
      "Deadmau5",
      "Above & Beyond",
      "Paul van Dyk",
      "Gareth Emery",
      "Markus Schulz",
      "Ferry Corsten",
      "Axwell",
      "ATB",
      "Sander Van Doorn",
      "Infected Mushroom",
      "Steve Angello",
      "Dash Berlin",
      "Sebastian Ingrosso",
      "Laidback Luke",
      "Judge Jules",
      "Afrojack",
      "Aly & Fila",
      "Fedde Le Grand",
      "Carl Cox",
      "Swedish House Mafia",
      "Cosmic Gate",
      "Bobina",
      "Benny Benassi",
      "Sasha",
      "Simon Patterson",
      "John Digweed",
      "Eric Prydz",
      "Richie Hawtin",
      "Andy Moor",
      "John O'Callaghan",
      "Roger Shah",
      "Kaskade",
      "Headhunterz",
      "Chuckie",
      "Bob Sinclair",
      "Avicii",
      "Kyau & Albert",
      "DJ Feel",
      "Moonbeam",
      "Joachim Garraud",
      "Daft Punk",
      "Lange",
      "Sean Tyas",
      "Eddie Halliwell",
      "Erick Morillo",
      "James Zabiela",
      "Umek",
      "Paul Oakenfold",
      "Matt Darey",
      "Mark Knight",
      "Richard Durand",
      "Martin Solveig",
      "tyDi",
      "Hernan Cattaneo",
      "Sven Vth",
      "Astrix",
      "Super8 & Tab",
      "Andy C",
      "Myon & Shane 54",
      "Marcel Woods",
      "Roger Sanchez",
      "Wally Lopez",
      "Mat Zo",
      "Marco V",
      "Leon Bolier",
      "Ronski Speed",
      "Wolfgang Gartner",
      "W&W",
      "Boys Noize",
      "D-Block & S-te-Fan",
      "Dubfire",
      "Dirty South",
      "John B",
      "Daniel Kandi",
      "Arty",
      "BT",
      "Boy George",
      "Pete Tha Zouk",
      "Fatboy Slim",
      "Skazi",
      "Paul Kalkbrenner",
      "Pete Tong",
      "Bloody Beetroots",
      "Arnej",
      "Joris Voorn",
      "Dada Life",
      "Noisecontrollers",
      "Showtek",
      "Laurent Wolf",
      "Claudia Cazacu",
      "Calvin Harris",
      "Luciano",
      "Marcus Schossow",
      "Sied Van Riel",
      "The Thrillseekers",
      "Justice",
      "DJ Vibe"
    ],
    "2011":[
      "David Guetta",
      "Armin Van Buuren",
      "Tiesto",
      "Deadmau5",
      "Above & Beyond",
      "Avicii",
      "Afrojack",
      "Dash Berlin",
      "Markus Schulz",
      "Swedish House Mafia",
      "Paul van Dyk",
      "Axwell",
      "Gareth Emery",
      "Fedde Le Grand",
      "ATB",
      "Sander Van Doorn",
      "Headhunterz",
      "Ferry Corsten",
      "Skrillex",
      "Laidback Luke",
      "Infected Mushroom",
      "Aly & Fila",
      "Steve Angello",
      "Hardwell",
      "Arty",
      "Sebastian Ingrosso",
      "Benny Benassi",
      "Daft Punk",
      "Martin Solveig",
      "Kaskade",
      "Carl Cox",
      "Chuckie",
      "Bob Sinclair",
      "Calvin Harris",
      "Noisecontrollers",
      "W&W",
      "Pete Tha Zouk",
      "Dada Life",
      "Angerfist",
      "D-Block & S-te-Fan",
      "Coone",
      "Steve Aoki",
      "Cosmic Gate",
      "Bobina",
      "Richie Hawtin",
      "Eric Prydz",
      "Zatox",
      "tyDi",
      "Orjan Nilsen",
      "Andy Moor",
      "Roger Shah",
      "John O'Callaghan",
      "Astrix",
      "Erick Morillo",
      "John Digweed",
      "Wolfgang Gartner",
      "DJ Feel",
      "Showtek",
      "Richard Durand",
      "Umek",
      "Skazi",
      "Paul Kalkbrenner",
      "Sasha",
      "Eddie Halliwell",
      "Moonbeam",
      "Myon & Shane 54",
      "Judge Jules",
      "Matt Darey",
      "Paul Oakenfold",
      "Alesso",
      "Mark Knight",
      "Sean Tyas",
      "Mat Zo",
      "Lange",
      "Joachim Garraud",
      "Simon Patterson",
      "Francis Davila",
      "Psyko Punkz",
      "Dimitri Vegas & Like Mike",
      "Wildstylez",
      "Roger Sanchez",
      "Hernan Cattaneo",
      "Tritonal",
      "DJ Vibe",
      "AN21",
      "Bloody Beetroots",
      "Felguk",
      "Nero",
      "Juanjo Martin",
      "Boy George",
      "Tenishia",
      "Sidney Samson",
      "Dirty South",
      "James Zabiela",
      "Marcel Woods",
      "Porter Robinson",
      "Sven Vth",
      "Brennan Heart",
      "Leon Bolier",
      "Boys Noize"
    ],
    "2012":[
      "Armin Van Buuren",
      "Tiesto",
      "Avicii",
      "David Guetta",
      "Deadmau5",
      "Hardwell",
      "Dash Berlin",
      "Above & Beyond",
      "Afrojack",
      "Skrillex",
      "Headhunterz",
      "Swedish House Mafia",
      "Markus Schulz",
      "Gareth Emery",
      "Steve Aoki",
      "Paul van Dyk",
      "Nicky Romero",
      "Sander Van Doorn",
      "Aly & Fila",
      "Alesso",
      "ATB",
      "Ferry Corsten",
      "Axwell",
      "Dada Life",
      "W&W",
      "Fedde Le Grand",
      "Noisecontrollers",
      "Arty",
      "Laidback Luke",
      "Kaskade",
      "Calvin Harris",
      "Orjan Nilsen",
      "Knife Party",
      "Sebastian Ingrosso",
      "Chuckie",
      "Zatox",
      "Coone",
      "Dimitri Vegas & Like Mike",
      "Cosmic Gate",
      "Porter Robinson",
      "Wildstylez",
      "Angerfist",
      "Infected Mushroom",
      "Daft Punk",
      "Carl Cox",
      "Nervo",
      "Pete Tha Zouk",
      "Martin Solveig",
      "Brennan Heart",
      "Tenishia",
      "Zedd",
      "Eric Prydz",
      "Bobina",
      "Madeon",
      "John O'Callaghan",
      "DJ Feel",
      "Steve Angello",
      "Omnia",
      "Umek",
      "Wolfgang Gartner",
      "AN21",
      "Tommy Trash",
      "Francis Davila",
      "D-Block & S-te-Fan",
      "Tritonal",
      "Bingo Players",
      "Psyko Punkz",
      "Shogun",
      "Paul Oakenfold",
      "Benny Benassi",
      "tyDi",
      "Mat Zo",
      "R3hab",
      "MOSIMANN",
      "Wasted Penguinz",
      "Dirty South",
      "Andrew Rayel",
      "Richie Hawtin",
      "Frontliner",
      "Myon & Shane 54",
      "Heatbeat",
      "Thomas Gold",
      "Nero",
      "Roger Shah",
      "Feed Me",
      "Mike Candys",
      "Andy Moor",
      "Ran-D",
      "Richard Durand",
      "Felguk",
      "Paul Kalkbrenner",
      "Moonbeam",
      "Sean Tyas",
      "Bob Sinclair",
      "Netsky",
      "Neelix",
      "Mark Knight",
      "John Digweed",
      "Da Tweekaz",
      "Project 46"
    ],
    "2013":[
      "Hardwell",
      "Armin Van Buuren",
      "Avicii",
      "Tiesto",
      "David Guetta",
      "Dimitri Vegas & Like Mike",
      "Nicky Romero",
      "Steve Aoki",
      "Afrojack",
      "Dash Berlin",
      "Skrillex",
      "Deadmau5",
      "Alesso",
      "W&W",
      "Calvin Harris",
      "Nervo",
      "Above & Beyond",
      "Sebastian Ingrosso",
      "Axwell",
      "Aly & Fila",
      "Markus Schulz",
      "Daft Punk",
      "Headhunterz",
      "Zedd",
      "Knife Party",
      "Swedish House Mafia",
      "Showtek",
      "Andrew Rayel",
      "Fedde Le Grand",
      "Dyro",
      "Laidback Luke",
      "Paul van Dyk",
      "ATB",
      "Angerfist",
      "Dada Life",
      "Kaskade",
      "Frontliner",
      "Steve Angello",
      "Sander Van Doorn",
      "Martin Garrix",
      "Porter Robinson",
      "Ferry Corsten",
      "Chuckie",
      "Krewella",
      "Coone",
      "Carl Cox",
      "Bobina",
      "Omnia",
      "Orjan Nilsen",
      "Zatox",
      "Gareth Emery",
      "Bingo Players",
      "Infected Mushroom",
      "Eric Prydz",
      "Tommy Trash",
      "Wildstylez",
      "Arty",
      "R3hab",
      "Madeon",
      "Vicetone",
      "Brennan Heart",
      "DJ Feel",
      "Gunz For Hire",
      "Diplo",
      "Tenishia",
      "Noisecontrollers",
      "Mike Candys",
      "Antoine",
      "MOSIMANN",
      "Project 46",
      "Blasterjaxx",
      "D-Block & S-te-Fan",
      "Dillon Francis",
      "Dannic",
      "Adaro",
      "Richie Hawtin",
      "Martin Solveig",
      "Felguk",
      "Myon & Shane 54",
      "Cosmic Gate",
      "Heatbeat",
      "John O'Callaghan",
      "Wasted Penguinz",
      "Tiddey",
      "Skazi",
      "Da Tweekaz",
      "Tenashar",
      "Bob Sinclair",
      "Benny Benassi",
      "Stafford Brothers",
      "Bl3nd",
      "Paul Oakenfold",
      "Mat Zo",
      "Diego Miranda",
      "DJs From Mars",
      "Matt Darey",
      "Umek",
      "Solarstone",
      "Ummet Ozcan",
      "Ran-D"
    ],
    "2014":[
      "Hardwell",
      "Dimitri Vegas & Like Mike",
      "Armin Van Buuren",
      "Martin Garrix",
      "Tiesto",
      "Avicii",
      "David Guetta",
      "Nicky Romero",
      "Skrillex",
      "Steve Aoki",
      "Calvin Harris",
      "Afrojack",
      "Blasterjaxx",
      "Dash Berlin",
      "Alesso",
      "Deadmau5",
      "Showtek",
      "W&W",
      "Deorro",
      "DVBBS",
      "Nervo",
      "Zedd",
      "R3hab",
      "Andrew Rayel",
      "Above & Beyond",
      "Steve Angello",
      "Dyro",
      "Aly & Fila",
      "Axwell",
      "Dannic",
      "Ummet Ozcan",
      "Diplo",
      "Krewella",
      "Oliver Heldens",
      "Fedde Le Grand",
      "Vicetone",
      "Angerfist",
      "Paul van Dyk",
      "Sebastian Ingrosso",
      "Headhunterz",
      "Borgore",
      "Kura",
      "Daft Punk",
      "Markus Schulz",
      "Frontliner",
      "Kaskade",
      "Brennan Heart",
      "Coone",
      "Infected Mushroom",
      "Laidback Luke",
      "Sander Van Doorn",
      "Dada Life",
      "Knife Party",
      "Dillon Francis",
      "Yves V",
      "Firebeatz",
      "Porter Robinson",
      "ATB",
      "Carl Cox",
      "Eric Prydz",
      "Gabry Ponte",
      "VINAI",
      "MAKJ",
      "Radical Redemption",
      "DJ Snake",
      "Da Tweekaz",
      "Noisecontrollers",
      "Carnage",
      "Cosmic Gate",
      "Diego Miranda",
      "Zatox",
      "MOSIMANN",
      "Tenishia",
      "Gareth Emery",
      "Umek",
      "Tiddey",
      "Zomboy",
      "Bl3nd",
      "Orjan Nilsen",
      "TJR",
      "3lau",
      "Don Diablo",
      "Madeon",
      "Wolfpack",
      "Mike Candys",
      "Quintino",
      "Borgeous",
      "Audien",
      "Boy George",
      "Richie Hawtin",
      "Ferry Corsten",
      "Code Black",
      "Heatbeat",
      "Merk & Kremont",
      "Wildstylez",
      "Bingo Players",
      "The Chainsmokers",
      "John O'Callaghan",
      "Arty",
      "Felguk"
    ],
    "2015":[
      "Dimitri Vegas & Like Mike",
      "Hardwell",
      "Martin Garrix",
      "Armin Van Buuren",
      "Tiesto",
      "David Guetta",
      "Avicii",
      "Afrojack",
      "Skrillex",
      "Steve Aoki",
      "Calvin Harris",
      "Oliver Heldens",
      "Alesso",
      "W&W",
      "Dash Berlin",
      "DVBBS",
      "Axwell & Ingrosso",
      "Nicky Romero",
      "Blasterjaxx",
      "Diplo",
      "R3hab",
      "Zedd",
      "KSHMR",
      "Nervo",
      "Deadmau5",
      "Dannic",
      "Dyro",
      "Deorro",
      "Above & Beyond",
      "Don Diablo",
      "Steve Angello",
      "DJ Snake",
      "Kygo",
      "Yves V",
      "Fedde Le Grand",
      "Ummet Ozcan",
      "Showtek",
      "Angerfist",
      "Bassjackers",
      "Andrew Rayel",
      "Paul van Dyk",
      "Aly & Fila",
      "VINAI",
      "Alok",
      "Jack U",
      "Tom Swoon",
      "Shogun",
      "Headhunterz",
      "Coone",
      "Vicetone",
      "Richie Hawtin",
      "Wolfpack",
      "Brennan Heart",
      "Major Lazer",
      "Porter Robinson",
      "Markus Schulz",
      "Eric Prydz",
      "Diego Miranda",
      "DJ Chetas",
      "Danny Avila",
      "Kura",
      "tchami",
      "Carl Cox",
      "Laidback Luke",
      "Disclosure",
      "Firebeatz",
      "Dillon Francis",
      "Borgore",
      "Daft Punk",
      "Umek",
      "Tenishia",
      "Radical Redemption",
      "Frontliner",
      "Borgeous",
      "Netsky",
      "Yellow Claw",
      "Chuckie",
      "Will Sparks",
      "Da Tweekaz",
      "Quintino",
      "Krewella",
      "ATB",
      "MAKJ",
      "Kaskade",
      "Ferry Corsten",
      "Flux Pavilion",
      "Zatox",
      "Carnage",
      "Robin Schulz",
      "Sander Van Doorn",
      "MaRLo",
      "Andy C",
      "MOSIMANN",
      "Miss K8",
      "Tujamo",
      "Mike Candys",
      "Swanky Tunes",
      "Galantis",
      "Cosmic Gate",
      "Knife Party"
    ],
    "2016":[
      "Martin Garrix",
      "Dimitri Vegas & Like Mike",
      "Hardwell",
      "Armin Van Buuren",
      "Tiesto",
      "David Guetta",
      "Steve Aoki",
      "Oliver Heldens",
      "Skrillex",
      "Afrojack",
      "Avicii",
      "KSHMR",
      "W&W",
      "Calvin Harris",
      "Don Diablo",
      "Axwell & Ingrosso",
      "Dash Berlin",
      "The Chainsmokers",
      "Ummet Ozcan",
      "Alesso",
      "R3hab",
      "DJ Snake",
      "Diplo",
      "DVBBS",
      "Alok",
      "Kygo",
      "Swanky Tunes",
      "Marshmello",
      "Nicky Romero",
      "Steve Angello",
      "Deadmau5",
      "Quintino",
      "DJ Chetas",
      "Bassjackers",
      "Zedd",
      "Headhunterz",
      "VINAI",
      "Florian Picasso",
      "Galantis",
      "Jack U",
      "Aly & Fila",
      "Shogun",
      "Blasterjaxx",
      "Major Lazer",
      "Nervo",
      "Angerfist",
      "Above & Beyond",
      "Yellow Claw",
      "MaRLo",
      "Fedde Le Grand",
      "Kura",
      "Lost Stories",
      "Deorro",
      "Vintage Culture",
      "Alan Walker",
      "Tom Swoon",
      "Coone",
      "Diego Miranda",
      "Brennan Heart",
      "Paul van Dyk",
      "ATB",
      "Yves V",
      "Wolfpack",
      "Dillon Francis",
      "Andrew Rayel",
      "Eric Prydz",
      "Felguk",
      "Radical Redemption",
      "Robin Schulz",
      "Dannic",
      "Da Tweekaz",
      "Daft Punk",
      "Will Sparks",
      "Carl Cox",
      "Timmy Trumpet",
      "Borgore",
      "Firebeatz",
      "Tujamo",
      "Laidback Luke",
      "Markus Schulz",
      "Vicetone",
      "Martin Jensen",
      "Jauz",
      "Carnage",
      "Netsky",
      "Carl Nunes",
      "Sam Feldt",
      "Miss K8",
      "Jay Hardway",
      "Porter Robinson",
      "Bobina",
      "Zatox",
      "Dyro",
      "Flume",
      "Infected Mushroom",
      "Showtek",
      "Daddy's Groove",
      "Martin Solveig",
      "Ferry Corsten",
      "DJ Feel"
    ],
    "2017":[
      "Martin Garrix",
      "Dimitri Vegas & Like Mike",
      "Armin Van Buuren",
      "Hardwell",
      "Tiesto",
      "The Chainsmokers",
      "David Guetta",
      "Afrojack",
      "Steve Aoki",
      "Marshmello",
      "Don Diablo",
      "KSHMR",
      "Oliver Heldens",
      "W&W",
      "Calvin Harris",
      "Skrillex",
      "Alan Walker",
      "R3hab",
      "Alok",
      "Dash Berlin",
      "Axwell Ingrosso",
      "DVBBS",
      "DJ Snake",
      "Kygo",
      "Diplo",
      "Lost Frequencies",
      "Above & Beyond",
      "Avicii",
      "Zedd",
      "Quintino",
      "Vintage Culture",
      "VINAI",
      "Headhunterz",
      "Eric Prydz",
      "Bassjackers",
      "Blasterjaxx",
      "Alesso",
      "Ummet Ozcan",
      "Fedde Le Grand",
      "Angerfist",
      "Wolfpack",
      "Nervo",
      "Timmy Trumpet",
      "Radical Redemption",
      "Major Lazer",
      "Tujamo",
      "Tom Swoon",
      "Kura",
      "Deadmau5",
      "Nicky Romero",
      "Paul van Dyk",
      "Danny Avila",
      "Aly & Fila",
      "ATB",
      "Yves V",
      "Diego Miranda",
      "Yellow Claw",
      "Miss K8",
      "Brennan Heart",
      "Mike Williams",
      "Dannic",
      "Carl Cox",
      "Carl Nunes",
      "Lucas & Steve",
      "Warface",
      "Galantis",
      "Da Tweekaz",
      "Jay Hardway",
      "Claptone",
      "Martin Jensen",
      "Florian Picasso",
      "Vini Vici",
      "Jauz",
      "Cat Dealers",
      "Sam Feldt",
      "Robin Schulz",
      "Andy C",
      "Carnage",
      "Andrew Rayel",
      "Richie Hawtin",
      "Solomun",
      "Steve Angello",
      "Will Sparks",
      "Mariana Bo",
      "Black Coffee",
      "Dillon Francis",
      "Flume",
      "Shogun",
      "Alison Wonderland",
      "Ferry Corsten",
      "Maceo Plex",
      "Carta",
      "MOSIMANN",
      "Julian Jordan",
      "tchami",
      "Porter Robinson",
      "Paul Kalkbrenner",
      "DJ L",
      "Swanky Tunes",
      "Disclosure"
    ],
    "2018": ["Martin Garrix",
    "Dimitri Vegas & Like Mike",
    "Hardwell",
    "Armin Van Buuren",
    "David Guetta",
    "Tiesto",
    "Don Diablo",
    "Afrojack",
    "Oliver Heldens",
    "Marshmello",
    "Steve Aoki",
    "R3hab",
    "Alok",
    "W&W",
    "Avicii",
    "DVBBS",
    "Lost Frequencies",
    "KSHMR",
    "Vintage Culture",
    "Eric Prydz",
    "Skrillex",
    "Fedde Le Grand",
    "Ummet Ozcan",
    "DJ Snake",
    "Quintino",
    "VINAI",
    "Nervo",
    "Headhunterz",
    "Angerfist",
    "Bassjackers",
    "The Chainsmokers",
    "Kygo",
    "Timmy Trumpet",
    "Vini Vici",
    "Wolfpack",
    "Alan Walker",
    "Blasterjaxx",
    "Danny Avila",
    "Kura",
    "Calvin Harris",
    "Axwell Ingrosso",
    "Diplo",
    "Nicky Romero",
    "Zedd",
    "Alesso",
    "Tujamo",
    "Yellow Claw",
    "Cat Dealers",
    "ATB",
    "Diego Miranda",
    "Above & Beyond",
    "Jeffrey Sutorius",
    "Carl Cox",
    "Martin Jensen",
    "Paul van Dyk",
    "Will Sparks",
    "Claptone",
    "Steve Angello",
    "Deadmau5",
    "Robin Schulz",
    "Richie Hawtin",
    "Florian Picasso",
    "Swedish House Mafia",
    "Jay Hardway",
    "Miss K8",
    "Mike Williams",
    "Andrew Rayel",
    "Mariana Bo",
    "Radical Redemption",
    "Brennan Heart",
    "Swanky Tunes",
    "MATTN",
    "Carta",
    "Aly & Fila",
    "Ferry Corsten",
    "Da Tweekaz",
    "Breathe Carolina",
    "Deniz Koyu // KO:YU",
    "Adam Beyer",
    "Daddy's Groove",
    "Mosimann",
    "tchami",
    "NGHTMRE",
    "DJ L",
    "Wildstylez",
    "Marco Carola",
    "Cedric Gervais",
    "MaRLo",
    "Deorro",
    "Andy C",
    "Solomun",
    "Lucas & Steve",
    "Markus Schulz",
    "Bobina",
    "Paul Kalkbrenner",
    "Alison Wonderland",
    "Nina Kraviz",
    "Rave Republic",
    "Carl Nunes",
    "SLANDER"],
    "2019":[
      "Dimitri Vegas & Like Mike",
      "Martin Garrix",
      "David Guetta",
      "Armin Van Buuren",
      "Marshmello",
      "Don Diablo",
      "Oliver Heldens",
      "Tiesto",
      "Afrojack",
      "Steve Aoki",
      "Alok",
      "Hardwell",
      "Timmy Trumpet",
      "R3hab",
      "KSHMR",
      "DJ Snake",
      "Eric Prydz",
      "W & W",
      "Calvin Harris",
      "Lost Frequencies",
      "Skrillex",
      "Above & Beyond",
      "DVBBS",
      "Nervo",
      "Quintino",
      "The Chainsmokers",
      "Alan Walker",
      "VINAI",
      "Headhunterz",
      "Fedde Le Grand",
      "Vini Vici",
      "Ummet Ozcan",
      "Angerfist",
      "Bassjackers",
      "Carl Cox",
      "Blasterjaxx",
      "Nicky Romero",
      "Wolfpack",
      "ATB",
      "Kura",
      "Danny Avila",
      "Swedish House Mafia",
      "Tujamo",
      "Alison Wonderland",
      "Martin Jensen",
      "Cat Dealers",
      "Vintage Culture",
      "Adam Beyer",
      "Mariana Bo",
      "Zedd",
      "MATTN",
      "Kygo",
      "Claptone",
      "Mike Williams",
      "Diego Miranda",
      "Yves V",
      "Will Sparks",
      "Steve Angello",
      "Ferry Corsten",
      "Nina Kraviz",
      "Alesso",
      "Breathe Carolina",
      "FISHER",
      "Illenium",
      "Deorro",
      "Richie Hawtin",
      "Diplo",
      "Da Tweekaz",
      "Miss K8",
      "3 Are Legend",
      "Deadmau5",
      "Carta",
      "Carl Nunes",
      "Charlotte de Witte",
      "Warface",
      "Cedric Gervais",
      "Yellow Claw",
      "Lucas & Steve",
      "Andy C",
      "Peggy Gou",
      "Deniz Koyu",
      "Robin Schulz",
      "Vicetone",
      "Tom & Collins",
      "Boris Brejcha",
      "Marco Carola",
      "Paul van Dyk",
      "Solardo",
      "Thomas Gold",
      "Black Coffee",
      "Paul Kalkbrenner",
      "Daddy's Groove",
      "Julian Jordan",
      "Rave Republic",
      "Sub Zero Project",
      "D.O.D",
      "Henri PFR",
      "Florian Picasso",
      "Swanky Tunes",
      "Solomun"
    ],
    "2020":[
      "David Guetta",
      "Dimitri Vegas & Like Mike",
      "Martin Garrix",
      "Armin Van Buuren",
      "Alok",
      "Don Diablo",
      "Afrojack",
      "Oliver Heldens",
      "Steve Aoki",
      "Timmy Trumpet",
      "Marshmello",
      "KSHMR",
      "R3hab",
      "W&W",
      "Skrillex",
      "Tiesto",
      "Hardwell",
      "Calvin Harris",
      "Above & Beyond",
      "Nervo",
      "Lost Frequencies",
      "Eric Prydz",
      "Fedde Le Grand",
      "Vini Vici",
      "DJ Snake",
      "Alan Walker",
      "The Chainsmokers",
      "Kygo",
      "Bassjackers",
      "Vintage Culture",
      "Nicky Romero",
      "Charlotte de Witte",
      "Quintino",
      "Carl Cox",
      "Zedd",
      "Angerfist",
      "Diplo",
      "Danny Avila",
      "VINAI",
      "Tujamo",
      "Claptone",
      "MATTN",
      "Illenium",
      "Mariana Bo",
      "Alesso",
      "Headhunterz",
      "Alison Wonderland",
      "Adam Beyer",
      "Wolfpack",
      "Paul van Dyk",
      "Diego Miranda",
      "Cat Dealers",
      "Ferry Corsten",
      "Miss K8",
      "DVBBS",
      "ATB",
      "REZZ",
      "Will Sparks",
      "Amelie Lens",
      "Boris Brejcha",
      "Carta",
      "3 Are Legend",
      "Breathe Carolina",
      "Deadmau5",
      "Ummet Ozcan",
      "Nina Kraviz",
      "Yellow Claw",
      "Jamie Jones",
      "Peggy Gou",
      "Blasterjaxx",
      "Julian Jordan",
      "Deniz Koyu",
      "Nora En Pure",
      "Kura",
      "Florian Picasso",
      "TBC - marek",
      "Tom & Collins",
      "Brennan Heart",
      "Mr Pig",
      "Radical Redemption",
      "Rave Republic",
      "Pink Panda",
      "D.O.D",
      "Swedish House Mafia",
      "Plastik Funk",
      "Green Velvet",
      "Sunnery James & Ryan Marciano",
      "Aryue",
      "Burak Yeter",
      "Mike Williams",
      "Black Coffee",
      "Tungevaag",
      "Deborah De Luca",
      "Mike Perry",
      "ANNA",
      "Dimitri Vangelis & Wyman",
      "Blastoyz",
      "22Bullets",
      "Robin Schulz",
      "Marco Carola"
    ],
    "2021":[
      "David Guetta",
      "Martin Garrix",
      "Armin Van Buuren",
      "Alok",
      "Dimitri Vegas & Like Mike",
      "Afrojack",
      "Don Diablo",
      "Oliver Heldens",
      "Timmy Trumpet",
      "Steve Aoki",
      "KSHMR",
      "R3hab",
      "Marshmello",
      "W&W",
      "Tiesto",
      "Calvin Harris",
      "Vintage Culture",
      "Nervo",
      "Fedde Le Grand",
      "Vini Vici",
      "Above & Beyond",
      "Alan Walker",
      "Charlotte de Witte",
      "Skrillex",
      "Lost Frequencies",
      "Nicky Romero",
      "Carl Cox",
      "Bassjackers",
      "The Chainsmokers",
      "Quintino",
      "Eric Prydz",
      "Claptone",
      "DJ Snake",
      "Danny Avila",
      "ATB",
      "Tujamo",
      "GORDO",
      "Peggy Gou",
      "MORTEN",
      "Mariana Bo",
      "Paul van Dyk",
      "Boris Brejcha",
      "Ummet Ozcan",
      "Amelie Lens",
      "REZZ",
      "Angerfist",
      "Diego Miranda",
      "Kygo",
      "Alison Wonderland",
      "Jamie Jones",
      "VINAI",
      "Deadmau5",
      "Miss K8",
      "Nina Kraviz",
      "Beauz",
      "Will Sparks",
      "Ferry Corsten",
      "Adam Beyer",
      "Nora En Pure",
      "Carta",
      "Blasterjaxx",
      "Breathe Carolina",
      "Alesso",
      "Zedd",
      "Pink Panda",
      "Julian Jordan",
      "MATTN",
      "Black Coffee",
      "Panta Q",
      "Mike Williams",
      "Deniz Koyu",
      "Naeleck",
      "Brennan Heart",
      "Kura",
      "Tom & Collins",
      "Mr Pig",
      "FISHER",
      "Virtual Riot",
      "D.O.D",
      "Plastik Funk",
      "Green Velvet",
      "Burak Yeter",
      "KAAZE",
      "Aryue",
      "Cat Dealers",
      "Rave Republic",
      "Sunnery James & Ryan Marciano",
      "MaRLo",
      "Tungevaag",
      "Giftback",
      "Christina Novelli",
      "22Bullets",
      "KAKA",
      "Blastoyz",
      "Florian Picasso",
      "Luminn",
      "Alexso",
      "Daddy's Groove",
      "Dexter King",
      "VIZE"
    ],
    "2022": [
      "Martin Garrix",
      "David Guetta",
      "Dimitri Vegas & Like Mike",
      "Alok",
      "Armin Van Buuren",
      "Afrojack",
      "Steve Aoki",
      "Timmy Trumpet",
      "Don Diablo",
      "Oliver Heldens",
      "Vintage Culture",
      "KSHMR",
      "R3hab",
      "Charlotte de Witte",
      "Ti\u00ebsto",
      "Calvin Harris",
      "Alan Walker",
      "W&W",
      "Fedde Le Grand",
      "Nicky Romero",
      "Vini Vici",
      "Carl Cox",
      "Skrillex",
      "Peggy Gou",
      "GORDO",
      "Marshmello",
      "Bassjackers",
      "Lost Frequencies",
      "Eric Prydz",
      "Above & Beyond",
      "Claptone",
      "Jamie Jones",
      "Quintino",
      "Mariana Bo",
      "Tujamo",
      "Danny Avila",
      "Amelie Lens",
      "Paul van Dyk",
      "Black Coffee",
      "Nervo",
      "Ummet Ozcan",
      "ATB",
      "Hardwell",
      "DJ Snake",
      "VINAI",
      "The Chainsmokers",
      "Alison Wonderland",
      "FISHER",
      "Reinier Zonneveld",
      "Deborah De Luca",
      "Adam Beyer",
      "Blasterjaxx",
      "Beauz",
      "Diego Miranda",
      "REZZ",
      "MORTEN",
      "Nora En Pure",
      "Zedd",
      "Carta",
      "Julian Jordan",
      "Boris Brejcha",
      "Will Sparks",
      "Angerfist",
      "Alesso",
      "Deadmau5",
      "Cat Dealers",
      "Joel Corry",
      "Brennan Heart",
      "Topic",
      "KAAZE",
      "Tom & Collins",
      "Plastik Funk",
      "Kura",
      "Naeleck",
      "Pink Panda",
      "Burak Yeter",
      "Swedish House Mafia",
      "MATTN",
      "Breathe Carolina",
      "Ofenbach",
      "Tungevaag",
      "Green Velvet",
      "22Bullets",
      "Lucas & Steve",
      "Mr Pig",
      "Aryue",
      "Ferry Corsten",
      "Solomun",
      "Miss K8",
      "Honey Dijon",
      "Acraze",
      "Le Twins",
      "Dubdogz",
      "Rave Republic",
      "KAKA",
      "Sunnery James & Ryan Marciano",
      "Maya Jane Coles",
      "Jay Hardway",
      "Cuebrick",
      "The Martinez Brothers"
    ]
  };
  
  export default userData;