import userData from "../../constants/data";
import axios from "axios";

async function createPlaylist(req, res) {
  try {
    let artists = [];

    //get user ID for playlist generation
    const userD = await axios.get(`https://api.spotify.com/v1/me`, {
              headers: {
                  Authorization: `Bearer ${req.body.token}`
              }
          }) 
    var userID = userD.data.id

    //create playlist store ID for later
    var playlistD = await axios({
      method: 'post',
      url: `https://api.spotify.com/v1/users/${userID}/playlists`,
      headers: { 'Authorization': 'Bearer ' + req.body.token },
      data: {
        "name": `${req.body.userInput} DJ Mag Top 100`,
        "description": "Playlist generated by Mark Kurpiel's spotify playlist generator web app using the top 100 artist of dj mag",
        "public": false
      }
    })
    var playlistID = playlistD.data.id
      
    //set and iterate through artist list       
    var artList = userData[req.body.userInput];
    var tempArt = []

    for (let i = 0; i < artList.length; i++) {

      //get artist spotify object from name
      let {data} = await axios.get("https://api.spotify.com/v1/search", {
                headers: {
                    'Content-Type' : "application/json",
                    'Authorization': `Bearer ${req.body.token}`
                },
                params: {
                    limit: 1,
                    q: artList[i],
                    type: "artist"
                }
            })
      let artID = data.artists.items[0].id;

      //creating artist list for carousel object later
      if(i<=10){
        tempArt.push({id:i+1, url:data.artists.items[0].images[0].url});
        //tempArt.push(data.artists.items[0]);
      }
      if(i==11){
        artists = tempArt;
      }

      //get top 10 track objects from artist name 
      let dataTrack = await axios.get(`https://api.spotify.com/v1/artists/${artID}/top-tracks`, {
                headers: {
                    Authorization: `Bearer ${req.body.token}`
                },
                params: {
                    limit: 10,
                    market: 'US'
                }
            })      
      let artistTracks = dataTrack.data.tracks;
      let trackURIs = artistTracks.map(v => v.uri);

      //add tracks to playlist created 
      await axios({
        method: 'post',
        url: `https://api.spotify.com/v1/playlists/${playlistID}/tracks`,
        headers: { 'Authorization': 'Bearer ' + req.body.token, 'Content-Type': 'application/json' },
        data: {
          "uris": trackURIs,
          "position": 0
        }
      })
    }
    
  } catch (error) {
    console.log(error);
    return res.status(error.statusCode || 500).json({ error: error.message });
  }

  return ((artists),res.status(200).json({ error: "" }));
}

export default createPlaylist;